export const CATEGORIES = [
    { label: 'World', value: 'World' },
    { label: 'Politics', value: 'Politics' },
    { label: 'Business', value: 'Business' },
    { label: 'Technology', value: 'Technology' },
    { label: 'Health', value: 'Health' },
    { label: 'Science', value: 'Science' },
    { label: 'Entertainment', value: 'Entertainment' },
    { label: 'Sports', value: 'Sports' },
    { label: 'Opinion', value: 'Opinion' },
    { label: 'Lifestyle', value: 'Lifestyle' },
    { label: 'Education', value: 'Education' },
    { label: 'Environment', value: 'Environment' },
    { label: 'Religion', value: 'Religion' },
    { label: 'Art & Culture', value: 'Art & Culture' },
    { label: 'Finance', value: 'Finance' },
    { label: 'Food', value: 'Food' },
    { label: 'Travel', value: 'Travel' },
    { label: 'Music', value: 'Music' },
    { label: 'Weather', value: 'Weather' },
    { label: 'Crime', value: 'Crime' },
    { label: 'Social Media', value: 'Social Media' },
    { label: 'Real Estate', value: 'Real Estate' },
    { label: 'Auto', value: 'Auto' },
    { label: 'Gaming', value: 'Gaming' },
    { label: 'Books', value: 'Books' },
    { label: 'Movies', value: 'Movies' },
    { label: 'TV', value: 'TV' },
    { label: 'Podcast', value: 'Podcast' },
    { label: 'Celebrity', value: 'Celebrity' },
    { label: 'Fashion', value: 'Fashion' },
];

//  this is my constant file